### ISSUE TITLE
Missing license?

### ISSUE THREAD

**Issue by Calinou** [timvideos/streaming-system#108]
I can't seem to find the license. Would you add one, please? See <http://choosealicense.com/> for more information.

**Comment by mithro** [comment]
@Calinou Thanks for filing this bug, sorry about taking so long to fix it. I've added a LICENSE file and some clarifying text in the README file (which I've included below);

----
Unless specified otherwise, code is licensed under the [Apache License, Version 2.0](http://www.apache.org/licenses/LICENSE-2.0).

This project makes extensive use of third party code from external projects.
For this code either LICENSE of COPYING file in the top level directory or the
file header for more information.

The website part of this system does use one non-free software component.
jwplayer (found in website/frontend/static/third_party/jwplayer/) is under a
CC-BY-NC 3.0 license. Work is underway to replace this dependency with a fully
open solution, see [Issue #60](https://github.com/timvideos/streaming-system/issues/60).
----
